site_name: LLM Task Framework
site_description: Generic framework for building LLM-powered task execution systems
site_url: https://github.com/MementoRC/llm-task-framework

repo_name: MementoRC/llm-task-framework
repo_url: https://github.com/MementoRC/llm-task-framework

theme:
  name: material
  palette:
    primary: deep purple
    accent: cyan

nav:
  - Home: index.md
  - Overview: overview.md
  - Development:
    - CI/CD Guide: cicd-guide.md
    - Git Flow: git-flow-workflow.md

markdown_extensions:
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false
  - admonition
  - pymdownx.details
  - pymdownx.superfences

docs_dir: docs
site_dir: site
